import {createApi, fetchBaseQuery} from "@reduxjs/toolkit/query/react"
import { baseURL } from "../../api/axios";



export const apiPlayerSlice:any = createApi({
    reducerPath:"player",
    baseQuery:fetchBaseQuery({baseUrl:baseURL}),
    tagTypes:['Player'],
    endpoints:(builder)=>({
        createGenre:builder.mutation<any,any>({
          query:(todo)=>({
            url:'/api/Genre/CreateGenre',
            method:"POST",
            body:todo
          }),
          invalidatesTags:['Player']
        }),
        getGenres:builder.query<any,any>({
          query:(todo)=>({
            url:'/api/Genre/GetAllGenres',
            method:"GET",
            body:todo
          }),
          providesTags:result=>['Player']
        }),
        getMainImageLinkForTrack:builder.query<any,any>({
          query:(todo)=>({
            url:'/api/Track/GetImageLinksByTrackId',
            method:"POST",
            body:todo
          }),
          providesTags:result=>['Player']
        }),
        getImageLinkByBase64:builder.mutation<any,any>({
          query:(todo)=>({
            url:'/api/Track/UploadImage',
            method:"POST",
            body:todo
          }),
          invalidatesTags:['Player']
        }),
        createTrack:builder.mutation<any,any>({
          query:(todo)=>({
            url:'/api/Track/CreateTrack',
            method:"POST",
            body:todo
          }),
          invalidatesTags:['Player']
        }),
        getTracks:builder.query<any,any>({
          query:(todo)=>({
            url:'/api/Track/GetAllTracks',
            method:"GET",
            body:todo
          }),
          providesTags:result=>['Player']
        }),
        getTracksByUserId:builder.query<any,any>({
          query:(todo)=>({
            url:'/api/Track/GetTracksByUserId',
            method:"POST",
            body:todo
          }),
          providesTags:result=>['Player']
        }),
        setLike:builder.mutation<any,any>({
          query:(todo)=>({
            url:'/api/Track/SetLikedTrack',
            method:"POST",
            body:todo
          }),
          invalidatesTags:['Player']
        }),
        getLikedTracksByUserId:builder.query<any,any>({
          query:(todo)=>({
            url:'/api/Track/GetLikedTracksByUserId',
            method:"POST",
            body:todo
          }),
          providesTags:result=>['Player']
        }),
        getTrackHistoryByUserId:builder.query<any,any>({
          query:(todo)=>({
            url:'/api/Track/GetTrackHistoryByUserId',
            method:"POST",
            body:todo
          }),
          providesTags:result=>['Player']
        }),
        addHistory:builder.mutation<any,any>({
          query:(todo)=>({
            url:'/api/Track/AddTrackHistory',
            method:"POST",
            body:todo
          }),
          invalidatesTags:['Player']
        }),
        deleteTrack:builder.mutation<any,any>({
          query:(todo)=>({
            url:'/api/Track/DeleteTrack',
            method:"POST",
            body:todo
          }),
          invalidatesTags:['Player']
        }),
        getTrackById:builder.query<any,any>({
          query:(todo)=>({
            url:'/api/Track/GetTrackById',
            method:"POST",
            body:todo
          }),
          providesTags:result=>['Player']
        }),
        getTrackCommentsByTrackId:builder.query<any,any>({
          query:(todo)=>({
            url:'/api/Track/GetTrackCommentsByTrackId',
            method:"POST",
            body:todo
          }),
          providesTags:result=>['Player']
        }),
        addTrackComment:builder.mutation<any,any>({
          query:(todo)=>({
            url:'/api/Track/AddTrackComment',
            method:"POST",
            body:todo
          }),
          invalidatesTags:['Player']
        }),
        getSearchTracksByName:builder.mutation<any,any>({
          query:(todo)=>({
            url:'/api/Track/GetSearchTracksByName',
            method:"POST",
            body:todo
          }),
          invalidatesTags:['Player']
        }),
        addAlbum:builder.mutation<any,any>({
          query:(todo)=>({
            url:'/api/Album/AddAlbum',
            method:"POST",
            body:todo
          }),
          invalidatesTags:['Player']
        }),
        getAlbumsByUserId:builder.query<any,any>({
          query:(todo)=>({
            url:'/api/Album/GetAlbumsByUserId',
            method:"POST",
            body:todo
          }),
          providesTags:result=>['Player']
        }),
        getTrackByIds:builder.query<any,any>({
          query:(todo)=>({
            url:'/api/Track/GetTrackByIds',
            method:"POST",
            body:todo
          }),
          providesTags:result=>['Player']
        }),
        createAlbum:builder.mutation<any,any>({
          query:(todo)=>({
            url:'/api/Album/AddAlbum',
            method:"POST",
            body:todo
          }),
          invalidatesTags:['Player']
        }),
        getAlbumById:builder.query<any,any>({
          query:(todo)=>({
            url:'/api/Album/GetAlbumById',
            method:"POST",
            body:todo
          }),
          providesTags:result=>['Player']
        }),
        subscribe:builder.mutation<any,any>({
          query:(todo)=>({
            url:'/api/Track/Subscribe',
            method:"POST",
            body:todo
          }),
          invalidatesTags:['Player']
        }),
        getSubscribersByUserId:builder.query<any,any>({
          query:(todo)=>({
            url:'/api/Track/GetSubscribers',
            method:"POST",
            body:todo
          }),
          providesTags:result=>['Player']
        }),
        getMySubscribesByUserId:builder.query<any,any>({
          query:(todo)=>({
            url:'/api/Track/GetMySubscribes',
            method:"POST",
            body:todo
          }),
          providesTags:result=>['Player']
        }),
        


    })
})


export const {
  useGetGenresQuery,
  useGetTracksQuery,
  useGetTracksByUserIdQuery,
  useGetLikedTracksByUserIdQuery,
  useGetTrackHistoryByUserIdQuery,
  useGetTrackByIdQuery,
  useGetTrackCommentsByTrackIdQuery,
  useGetAlbumsByUserIdQuery,
  useGetTrackByIdsQuery,
  useGetAlbumByIdQuery,
  useGetSubscribersByUserIdQuery,
  useGetMySubscribesByUserIdQuery,
} = apiPlayerSlice

